# Generated by Django 4.2.5 on 2025-03-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], default='m', max_length=1),
        ),
    ]
